# Generated by Django 4.2.5 on 2023-11-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='number',
            new_name='spot_number',
        ),
    ]
