# Generated by Django 4.2.5 on 2023-11-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0002_rename_number_spot_spot_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='isPaid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='isTaken',
            new_name='is_taken',
        ),
    ]
