# Generated by Django 4.2.5 on 2023-12-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0006_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Shops',
        ),
    ]
