# Generated by Django 4.2.5 on 2023-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0007_rename_shop_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
