# Generated by Django 4.2.5 on 2023-12-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0008_alter_parking_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shops',
        ),
    ]
