# Generated by Django 4.2.5 on 2023-12-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='parking_id',
            new_name='parking',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='user_id',
            new_name='user',
        ),
    ]
